name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:24.0

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout all history for all branches and tags
        fetch-depth: 0
    - name: Current Directory
      run:  pwd
    - name: Git
      run:  ls -l .git/refs/heads/*
    - name: Install gawk
      run:  apt update && apt install sudo && sudo apt-get install gawk
    - name: Compile
      run:  make
    - name: Run tests
      run:  make eunit
    - name: Make documentation
      run:  make gh-pages
