name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:24.0

    steps:
    - uses: actions/checkout@v2
    - name: Install gawk
      run:  apt update && apt install sudo && sudo apt-get install gawk
    - name: Compile
      run:  make
    - name: Run tests
      run:  make eunit
    - name: Make documentation
      run:  |
            git config user.name  github-actions
            git config user.email github-actions@github.com
            make gh-pages
