name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25.2

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout all history for all branches and tags
        fetch-depth: 0
#    - uses: actions/setup-elixir@v1
#      with:
#        otp-version: '24.0'
#        elixir-version: '1.13.2'
    - name: Current Directory
      run:  pwd
    - name: Compile
      run:  make
    - name: Run tests
      run:  make eunit
