on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: erlang:25.2

    steps:
      - name: Make documentation
        run:  make docs
      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          cat Makefile
          make publish noconfirm=true
