on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: erlang:25.2

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - name: Print tag name
        run:  git describe --tags --abbrev=0
      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run:  rebar3 hex publish -r hexpm --yes --replace
